# Curated Montreal buy-side / investment employers: (name, website domain, category)
# category: pension | pe_vc | hedge | am | ib | markets | insurer | corpdev | advisory
SEED = [
    # ---- pension & institutional investors
    ("CDPQ", "cdpq.com", "pension"),
    ("PSP Investments", "investpsp.com", "pension"),
    ("Ivanhoe Cambridge", "ivanhoecambridge.com", "pension"),
    ("Fonds de solidarite FTQ", "fondsftq.com", "pension"),
    ("Fondaction", "fondaction.com", "pension"),
    ("Investissement Quebec", "investquebec.com", "pension"),
    ("BDC", "bdc.ca", "pe_vc"),
    ("Teralys Capital", "teralyscapital.com", "pe_vc"),
    ("Power Corporation", "powercorporation.com", "pe_vc"),
    ("Sagard", "sagard.com", "pe_vc"),
    ("Power Sustainable", "powersustainable.com", "pe_vc"),
    ("Claridge", "claridge.ca", "pe_vc"),
    ("Ardian", "ardian.com", "pe_vc"),
    ("Desjardins Capital", "desjardinscapital.com", "pe_vc"),
    ("CN Investment Division", "cn.ca", "pension"),
    ("OMERS", "omers.com", "pension"),
    ("CPP Investments", "cppinvestments.com", "pension"),
    ("Ontario Teachers", "otpp.com", "pension"),
    ("BCI", "bci.ca", "pension"),
    ("AIMCo", "aimco.ca", "pension"),
    # ---- private equity
    ("Novacap", "novacap.ca", "pe_vc"),
    ("Walter Capital Partners", "waltercapital.ca", "pe_vc"),
    ("Champlain Financial", "champlainfinancial.com", "pe_vc"),
    ("XPND Capital", "xpndcapital.com", "pe_vc"),
    ("Seafort Capital", "seafortcapital.com", "pe_vc"),
    ("Brookfield", "brookfield.com", "pe_vc"),
    ("Onex", "onex.com", "pe_vc"),
    ("Birch Hill Equity", "birchhillequity.com", "pe_vc"),
    ("Clairvest", "clairvest.com", "pe_vc"),
    ("TorQuest", "torquest.com", "pe_vc"),
    ("Persistence Capital", "persistencecapital.com", "pe_vc"),
    ("Northleaf Capital", "northleafcapital.com", "pe_vc"),
    ("HarbourVest", "harbourvest.com", "pe_vc"),
    ("Hamilton Lane", "hamiltonlane.com", "pe_vc"),
    ("StepStone", "stepstonegroup.com", "pe_vc"),
    ("Blackstone", "blackstone.com", "pe_vc"),
    ("KKR", "kkr.com", "pe_vc"),
    # ---- venture capital
    ("Inovia Capital", "inovia.vc", "pe_vc"),
    ("Real Ventures", "realventures.com", "pe_vc"),
    ("Panache Ventures", "panache.vc", "pe_vc"),
    ("White Star Capital", "whitestarcapital.com", "pe_vc"),
    ("Amplitude Ventures", "amplitudevc.com", "pe_vc"),
    ("Lumira Ventures", "lumiraventures.com", "pe_vc"),
    ("Cycle Capital", "cyclecapital.com", "pe_vc"),
    ("Diagram Ventures", "diagram.vc", "pe_vc"),
    ("Brightspark Ventures", "brightspark.com", "pe_vc"),
    ("Luge Capital", "luge.vc", "pe_vc"),
    ("Tactico", "tactico.ca", "pe_vc"),
    ("Front Row Ventures", "frontrow.vc", "pe_vc"),
    ("Anges Quebec", "angesquebec.com", "pe_vc"),
    ("TVM Life Science", "tvm-lifescience.com", "pe_vc"),
    ("Georgian", "georgian.io", "pe_vc"),
    ("Boreal Ventures", "borealventures.ca", "pe_vc"),
    ("Evolem", "evolem.com", "pe_vc"),
    ("Emerillon Capital", "emerillon.com", "pe_vc"),
    ("Idealist Capital", "idealistcapital.com", "pe_vc"),
    # ---- asset managers
    ("Fiera Capital", "fieracapital.com", "am"),
    ("Jarislowsky Fraser", "jflglobal.com", "am"),
    ("Letko Brosseau", "letko.com", "am"),
    ("Van Berkom", "vanberkom.com", "am"),
    ("Montrusco Bolton", "montrusco.com", "am"),
    ("Triasima", "triasima.com", "am"),
    ("Claret Asset Management", "claret.ca", "am"),
    ("Pembroke Management", "pml.ca", "am"),
    ("Addenda Capital", "addenda-capital.com", "am"),
    ("AlphaFixe Capital", "alphafixe.com", "am"),
    ("Optimum Asset Management", "optimumgestion.com", "am"),
    ("Formula Growth", "formulagrowth.ca", "am"),
    ("Mackenzie Investments", "mackenzieinvestments.com", "am"),
    ("Connor Clark & Lunn", "cclgroup.com", "am"),
    ("Hexavest (Vontobel)", "vontobel.com", "am"),
    ("Natixis Investment Managers", "im.natixis.com", "am"),
    ("Picton Mahoney", "pictonmahoney.com", "am"),
    ("Mawer", "mawer.com", "am"),
    ("Beutel Goodman", "beutelgoodman.com", "am"),
    ("Burgundy Asset Management", "burgundyasset.com", "am"),
    ("Guardian Capital", "guardiancapital.com", "am"),
    ("PIMCO", "pimco.com", "am"),
    ("BlackRock", "blackrock.com", "am"),
    ("State Street", "statestreet.com", "am"),
    # ---- insurers' investment arms
    ("iA Financial Group", "ia.ca", "insurer"),
    ("Beneva", "beneva.ca", "insurer"),
    ("Manulife", "manulife.com", "insurer"),
    ("Sun Life", "sunlife.ca", "insurer"),
    ("Intact", "intactfc.com", "insurer"),
    ("Desjardins", "desjardins.com", "ib"),
    # ---- trading / hedge funds
    ("Squarepoint", "squarepoint-capital.com", "hedge"),
    ("DRW", "drw.com", "hedge"),
    ("Hudson River Trading", "hudsonrivertrading.com", "hedge"),
    ("Optiver", "optiver.com", "hedge"),
    # ---- banks, capital markets, dealers
    ("National Bank", "bnc.ca", "ib"),
    ("BMO", "bmo.com", "ib"),
    ("RBC", "rbc.com", "ib"),
    ("TD", "td.com", "ib"),
    ("CIBC", "cibc.com", "ib"),
    ("Scotiabank", "scotiabank.com", "ib"),
    ("Laurentian Bank", "laurentianbank.ca", "ib"),
    ("Canaccord Genuity", "canaccordgenuity.com", "ib"),
    ("Raymond James", "raymondjames.ca", "ib"),
    ("Stifel", "stifel.com", "ib"),
    ("Eight Capital", "eightcapital.com", "ib"),
    ("Cormark Securities", "cormark.com", "ib"),
    ("Echelon", "echelonpartners.ca", "ib"),
    ("BNP Paribas", "bnpparibas.ca", "ib"),
    ("Morgan Stanley", "morganstanley.com", "ib"),
    ("Credit Agricole CIB", "ca-cib.com", "ib"),
    ("Societe Generale", "societegenerale.com", "ib"),
    ("TMX Group", "tmx.com", "markets"),
    # ---- advisory (deal / valuation teams)
    ("Deloitte", "deloitte.com", "advisory"),
    ("PwC", "pwc.com", "advisory"),
    ("EY", "ey.com", "advisory"),
    ("KPMG", "kpmg.com", "advisory"),
    ("BDO", "bdo.ca", "advisory"),
    ("Raymond Chabot Grant Thornton", "rcgt.com", "advisory"),
    ("MNP", "mnp.ca", "advisory"),
    ("Richter", "richter.ca", "advisory"),
    ("Alvarez & Marsal", "alvarezandmarsal.com", "advisory"),
    ("Houlihan Lokey", "hl.com", "advisory"),
    ("Lazard", "lazard.com", "advisory"),
    ("Evercore", "evercore.com", "advisory"),
    ("PJT Partners", "pjtpartners.com", "advisory"),
    ("Moelis", "moelis.com", "advisory"),
    ("Rothschild", "rothschildandco.com", "advisory"),
    # ---- corporate development at Montreal companies
    ("Couche-Tard", "couche-tard.com", "corpdev"),
    ("CGI", "cgi.com", "corpdev"),
    ("CAE", "cae.com", "corpdev"),
    ("WSP", "wsp.com", "corpdev"),
    ("BRP", "brp.com", "corpdev"),
    ("Saputo", "saputo.com", "corpdev"),
    ("Metro", "metro.ca", "corpdev"),
    ("Dollarama", "dollarama.com", "corpdev"),
    ("Air Canada", "aircanada.com", "corpdev"),
    ("CN", "cn.ca", "corpdev"),
    ("Bombardier", "bombardier.com", "corpdev"),
    ("Lightspeed", "lightspeedhq.com", "corpdev"),
    ("Nuvei", "nuvei.com", "corpdev"),
    ("Hydro-Quebec", "hydroquebec.com", "corpdev"),
    ("Gildan", "gildancorp.com", "corpdev"),
    ("Stella-Jones", "stella-jones.com", "corpdev"),
    ("Boralex", "boralex.com", "corpdev"),
    ("Innergex", "innergex.com", "corpdev"),
    ("Pomerleau", "pomerleau.ca", "corpdev"),
    ("Cogeco", "corpo.cogeco.com", "corpdev"),
    ("Quebecor", "quebecor.com", "corpdev"),
    ("TFI International", "tfiintl.com", "corpdev"),
    ("Aritzia", "aritzia.com", "corpdev"),
]
